# Generated by Django 4.0.1 on 2022-04-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCacthModel',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='email')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
            ],
        ),
    ]
